-   id: parisneo-python-check
    name: ParisNeo Python Style Check
    description: Enforces ParisNeo's Python coding standards
    entry: parisneo-python-check
    language: python
    types: [python]
    additional_dependencies: [.]

-   id: parisneo-js-check
    name: ParisNeo JavaScript Style Check
    description: Enforces ParisNeo's JavaScript coding standards
    entry: parisneo-js-check
    language: python
    types: [javascript]
    additional_dependencies: [.]
