name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
        npm install -g eslint prettier
        
    - name: Run tests
      run: pytest
        
    - name: Run hooks
      run: |
        pip install pre-commit
        pre-commit run --all-files
